### model
# model_name_or_path: /mnt/workspace/zpf/.cache/Qwen2.5-7B-Instruct
model_name_or_path: /mnt/workspace/zpf/.cache/Qwen2.5-14B-Instruct

### method
stage: sft
do_train: true
finetuning_type: lora
lora_target: all
lora_rank: 16
lora_alpha: 16
lora_dropout: 0.05

### dataset
dataset: foodsky_new, alpaca_zh_demo, glaive_toolcall_zh_demo, alpaca_data_zh_51k, Auto-CoT, wiki_agriculture
template: qwen
cutoff_len: 14240
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: saves/foodsky-14b/lora/sft0
logging_steps: 100
save_steps: 100
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 2
gradient_accumulation_steps: 16
learning_rate: 1.0e-6
num_train_epochs: 1.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### eval
val_size: 0.1
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 500
